# Copyright 2021 The Cross-Media Measurement Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Build and test all Bazel targets in the specified Bazel workspaces.

name: Build and test Bazel targets

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  any-sketch:
    name: Build and test any-sketch targets
    runs-on: ubuntu-20.04
    steps:
    - name: Check out revision
      uses: actions/checkout@v2

    - name: Bazel build and test
      uses: ./.github/actions/bazel-build-test
      with:
        workspace-path: ${{ github.job }}
  any-sketch-java:
    name: Build and test any-sketch-java targets
    runs-on: ubuntu-20.04
    steps:
    - name: Check out revision
      uses: actions/checkout@v2

    - name: Bazel build and test
      uses: ./.github/actions/bazel-build-test
      with:
        workspace-path: ${{ github.job }}
  cross-media-measurement:
    name: Build and test cross-media-measurement targets
    runs-on: ubuntu-20.04
    steps:
    - name: Check out revision
      uses: actions/checkout@v2

    - name: Bazel build and test
      uses: ./.github/actions/bazel-build-test
      with:
        workspace-path: ${{ github.job }}
  cross-media-measurement-api:
    name: Build and test cross-media-measurement-api targets
    runs-on: ubuntu-20.04
    steps:
    - name: Check out revision
      uses: actions/checkout@v2

    - name: Bazel build and test
      uses: ./.github/actions/bazel-build-test
      with:
        workspace-path: ${{ github.job }}
  examples:
    name: Build and test examples targets
    runs-on: ubuntu-20.04
    steps:
    - name: Check out revision
      uses: actions/checkout@v2

    - name: Bazel build and test
      uses: ./.github/actions/bazel-build-test
      with:
        workspace-path: ${{ github.job }}
